---
roles:
  - name: geerlingguy.docker
    version: 7.1.0

  - name: geerlingguy.nfs
    version: 2.0.0

  - name: geerlingguy.security
    version: 2.2.0

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general
  - name: vladgh.samba
