---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - include_vars:
        file: ../../defaults/main.yml

    - name: Get container state
      docker_container_info:
        name: "{{ calibreweb_container_name }}"
      register: result

<<<<<<< HEAD
    - name: Check Calibre-web is running
=======
    - name: Check Calibre is running
>>>>>>> b6ac9743 (rename misnamed calibre role to calibreweb)
      assert:
        that:
          - result.container['State']['Status'] == "running"
          - result.container['State']['Restarting'] == false
