---
# This is a Hello World playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Try and stop and remove Hello World
      community.docker.docker_container:
        name: "{{ flame_container_name }}"
        state: absent
      register: result

    - name: Check flame is stopped
      ansible.builtin.assert:
        that:
          - not result.changed
