---
flame_enabled: false
flame_available_externally: false

# directories
flame_data_directory: "{{ docker_home }}/flame"

# network
flame_port: "5005"
flame_hostname: "flame"

flame_image_name: "pawelmalak/flame"
flame_image_version: "latest"

# specs
flame_memory: 1g

# docker
flame_container_name: flame
